addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
script:
    bash test.sh
